### ISSUE TITLE
Default decalaration

### ISSUE THREAD

**Issue by IonutLascu** [theodor96/shared-ptr#1]
No default constructor exists for class `SharedPtr<T>`; I am trying to declare ` SharedPtr<int> sp;`

**Comment by theodor96** [comment]
Going to open a PR so that you can comment on any line you would like. Also, noted the issue, will fix.

Here  is the PR: https://github.com/theodor96/shared-ptr/pull/3

**Comment by theodor96** [comment]
Closed with  [PR#3.](https://github.com/theodor96/shared-ptr/pull/3)
